---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: iscsi-csi-snapshots
driver: org.democratic-csi.synology-iscsi
deletionPolicy: Delete
parameters:
  detachedSnapshots: "false"
