---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher
  namespace: cattle-system
spec:
  secretName: rancher-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: rancher.${SECRET_DOMAIN}
  dnsNames:
    - rancher.${SECRET_DOMAIN}
