---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teslamate-init-db
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: teslamate-init-db
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: INIT_POSTGRES_HOST
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SERVER
    - secretKey: INIT_POSTGRES_DBNAME
      remoteRef:
        key: teslamate
        property: DATABASE_NAME
    - secretKey: INIT_POSTGRES_SUPER_PASS
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SUPER_PASS
    - secretKey: INIT_POSTGRES_USER
      remoteRef:
        key: teslamate
        property: TESLAMATE_POSTGRES_USER
    - secretKey: INIT_POSTGRES_PASS
      remoteRef:
        key: teslamate
        property: TESLAMATE_POSTGRES_PASS
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teslamate
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: teslamate-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: teslamate
        property: TESLAMATE_ENCRYPTION_KEY
    - secretKey: DATABASE_NAME
      remoteRef:
        key: teslamate
        property: DATABASE_NAME
    - secretKey: DATABASE_HOST
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SERVER
    - secretKey: DATABASE_PASS
      remoteRef:
        key: teslamate
        property: TESLAMATE_POSTGRES_PASS
    - secretKey: DATABASE_USER
      remoteRef:
        key: teslamate
        property: TESLAMATE_POSTGRES_USER

