---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    - secretKey: GF_DATABASE_HOST
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SERVER
    - secretKey: TESLAMATE_DB_HOST
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SERVER
    - secretKey: TESLAMATE_DB_NAME
      remoteRef:
        key: teslamate
        property: DATABASE_NAME
    - secretKey: TESLAMATE_DB_USER
      remoteRef:
        key: teslamate
        property: TESLAMATE_POSTGRES_USER
    - secretKey: TESLAMATE_DB_PASS
      remoteRef:
        key: teslamate
        property: TESLAMATE_POSTGRES_PASS
