---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Namespace is safe to create
  - ./namespace.yaml
  - ./mosquitto/ks.yaml
  - ./home-assistant/ks.yaml
  # - ./frigate/ks.yaml