---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config-base
data:
  configuration.yaml: |
    homeassistant:
      name: Home
      unit_system: imperial
      time_zone: America/Denver
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.69.0.0/16
        - 10.0.0.0/24
        - 127.0.0.1
    default_config:
