apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-pvc-migrate
  namespace: mealie
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi-csi
  resources:
    requests:
      storage: 1Gi
