---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pvc-snapshotter
  namespace: storage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvc-snapshotter
rules:
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pvc-snapshotter
subjects:
  - kind: ServiceAccount
    name: pvc-snapshotter
    namespace: storage
roleRef:
  kind: ClusterRole
  name: pvc-snapshotter
  apiGroup: rbac.authorization.k8s.io
